# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_transcriber.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17\x61udio_transcriber.proto""\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c"T\n\x15TranscriptionResponse\x12\x15\n\rtranscription\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x01"\x14\n\x12HealthCheckRequest"*\n\x13HealthCheckResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32Y\n\x17\x41udioTranscriberService\x12>\n\x0fTranscribeAudio\x12\r.AudioRequest\x1a\x16.TranscriptionResponse"\x00(\x01\x30\x01\x32J\n\x12HealthCheckService\x12\x34\n\x05\x43heck\x12\x13.HealthCheckRequest\x1a\x14.HealthCheckResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "audio_transcriber_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_AUDIOREQUEST"]._serialized_start = 27
    _globals["_AUDIOREQUEST"]._serialized_end = 61
    _globals["_TRANSCRIPTIONRESPONSE"]._serialized_start = 63
    _globals["_TRANSCRIPTIONRESPONSE"]._serialized_end = 147
    _globals["_HEALTHCHECKREQUEST"]._serialized_start = 149
    _globals["_HEALTHCHECKREQUEST"]._serialized_end = 169
    _globals["_HEALTHCHECKRESPONSE"]._serialized_start = 171
    _globals["_HEALTHCHECKRESPONSE"]._serialized_end = 213
    _globals["_AUDIOTRANSCRIBERSERVICE"]._serialized_start = 215
    _globals["_AUDIOTRANSCRIBERSERVICE"]._serialized_end = 304
    _globals["_HEALTHCHECKSERVICE"]._serialized_start = 306
    _globals["_HEALTHCHECKSERVICE"]._serialized_end = 380
# @@protoc_insertion_point(module_scope)
