# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import audio_transcriber_pb2 as audio__transcriber__pb2


class AudioTranscriberServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeAudio = channel.stream_stream(
            "/AudioTranscriberService/TranscribeAudio",
            request_serializer=audio__transcriber__pb2.AudioRequest.SerializeToString,
            response_deserializer=audio__transcriber__pb2.TranscriptionResponse.FromString,
        )


class AudioTranscriberServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TranscribeAudio(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AudioTranscriberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "TranscribeAudio": grpc.stream_stream_rpc_method_handler(
            servicer.TranscribeAudio,
            request_deserializer=audio__transcriber__pb2.AudioRequest.FromString,
            response_serializer=audio__transcriber__pb2.TranscriptionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "AudioTranscriberService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class AudioTranscriberService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranscribeAudio(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/AudioTranscriberService/TranscribeAudio",
            audio__transcriber__pb2.AudioRequest.SerializeToString,
            audio__transcriber__pb2.TranscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )


class HealthCheckServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
            "/HealthCheckService/Check",
            request_serializer=audio__transcriber__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=audio__transcriber__pb2.HealthCheckResponse.FromString,
        )


class HealthCheckServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_HealthCheckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Check": grpc.unary_unary_rpc_method_handler(
            servicer.Check,
            request_deserializer=audio__transcriber__pb2.HealthCheckRequest.FromString,
            response_serializer=audio__transcriber__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "HealthCheckService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class HealthCheckService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/HealthCheckService/Check",
            audio__transcriber__pb2.HealthCheckRequest.SerializeToString,
            audio__transcriber__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
